//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelUnlock.Properties {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelUnlock.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Done.
        /// </summary>
        internal static string EXCRepFinished {
            get {
                return ResourceManager.GetString("EXCRepFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Path cannot be empty..
        /// </summary>
        internal static string EXExcEmptyPath {
            get {
                return ResourceManager.GetString("EXExcEmptyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Path to Temp folder is empty..
        /// </summary>
        internal static string EXExcEmptyTempPath {
            get {
                return ResourceManager.GetString("EXExcEmptyTempPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný File isnt exist..
        /// </summary>
        internal static string EXExcFileNoExist {
            get {
                return ResourceManager.GetString("EXExcFileNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný It is not possible to create a temporary file. .
        /// </summary>
        internal static string EXExcFullTemp {
            get {
                return ResourceManager.GetString("EXExcFullTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Temp folder isnt exist..
        /// </summary>
        internal static string EXExcTempPath {
            get {
                return ResourceManager.GetString("EXExcTempPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Extension must be .
        /// </summary>
        internal static string EXExcWrongExtension {
            get {
                return ResourceManager.GetString("EXExcWrongExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Clean the temporary folder..
        /// </summary>
        internal static string EXReClearTemp {
            get {
                return ResourceManager.GetString("EXReClearTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Completes file..
        /// </summary>
        internal static string EXReCompleting {
            get {
                return ResourceManager.GetString("EXReCompleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Copying to temp folder..
        /// </summary>
        internal static string EXReCopyTemp {
            get {
                return ResourceManager.GetString("EXReCopyTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Checking files..
        /// </summary>
        internal static string EXRepCheck {
            get {
                return ResourceManager.GetString("EXRepCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Prepare for completion..
        /// </summary>
        internal static string EXRePrepComplet {
            get {
                return ResourceManager.GetString("EXRePrepComplet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Returning file..
        /// </summary>
        internal static string EXReSendingBack {
            get {
                return ResourceManager.GetString("EXReSendingBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Unlocking sheet..
        /// </summary>
        internal static string EXReUnlockList {
            get {
                return ResourceManager.GetString("EXReUnlockList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Unlocking sheets..
        /// </summary>
        internal static string EXReUnlockLists {
            get {
                return ResourceManager.GetString("EXReUnlockLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Unlocking excel..
        /// </summary>
        internal static string EXReUnpackEx {
            get {
                return ResourceManager.GetString("EXReUnpackEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (unlocked).
        /// </summary>
        internal static string EXUnlockedTag {
            get {
                return ResourceManager.GetString("EXUnlockedTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný  Drop file here of write path..
        /// </summary>
        internal static string FMCoDropItemHere {
            get {
                return ResourceManager.GetString("FMCoDropItemHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Error.
        /// </summary>
        internal static string FMCoError {
            get {
                return ResourceManager.GetString("FMCoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Set path..
        /// </summary>
        internal static string FMCoErrorSetPath {
            get {
                return ResourceManager.GetString("FMCoErrorSetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Path to excel.
        /// </summary>
        internal static string FMExcelPath {
            get {
                return ResourceManager.GetString("FMExcelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Excel Unlock - V.
        /// </summary>
        internal static string FMTitle {
            get {
                return ResourceManager.GetString("FMTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Unlock.
        /// </summary>
        internal static string FMUnlock {
            get {
                return ResourceManager.GetString("FMUnlock", resourceCulture);
            }
        }
    }
}
